- gatsby-config.js
> sitemap.xml 버그 수정: 영어 페이지 주소 변경됨.

- src/components/mobile-header.js
> hotfix. 잘못된 위치에서 import함.

- src/components/common.js
- src/components/constants.js
- src/components/mobile-layout.js
- src/components/mobile-pricing.js
- 키워드 광고로 들어온 유저의 경우 다운로드 전환을 체크하기 위해 링크를 변경.
- google : gclid
- naver : n_media
> 키워드 광고로 접속한 유저의 경우 다른 appmetrica링크 노출

- README.md
- gatsby-browser.js
- gatsby-config.js
- gatsby-ssr.js
- package.json
- src/boot.js
- src/components/common.js
- src/components/constants.js
- src/components/desktop-about.js
- src/components/desktop-features.js
- src/components/desktop-footer.js
- src/components/desktop-header.js
- src/components/desktop-index.js
- src/components/desktop-layout.js
- src/components/desktop-pricing.js
- src/components/helpscout.js
- src/components/mobile-about.js
- src/components/mobile-features.js
- src/components/mobile-footer.js
- src/components/mobile-index.js
- src/components/mobile-layout.js
- src/components/mobile-pricing.js
- src/components/seo.js
- src/media.js
- src/pages/404.js
- src/pages/about.js
- src/pages/features.js
- src/pages/index.js
- src/pages/pricing.js
- prettier 적용. jsx-max-props-per-line 이 1 이 보장되지 않는건 무지 마음에 안들지만 일단 적용해봄.
- react class -> function component로 변경.
> prettier 일괄 적용

- src/components/constants.js
> search ad tracking url변경

- static/naver278d14a46b0c9d4fea90a72711fd20b1.html
> 네이버 웹마스터 인증

- src/components/common.js
- src/components/constants.js
- src/components/mobile-features.js
- src/components/mobile-pricing.js
> 앱 다운로드 트래킹 url

- gatsby-config.js
- gatsby-ssr.js
- src/components/desktop-marketing.js
- src/components/mobile-marketing.js
- src/components/seo.js
- src/fragments.js
- src/pages/404.js
- src/pages/about.js
- src/pages/features.js
- src/pages/index.js
- src/pages/marketing.js
- src/pages/pricing.js
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.boxhero-app.com%2F
> 페이스북 og meta 데이터 워닝 수정

- README.md
- gatsby-config.js
- package.json
- src/components/desktop-about.js
- src/components/desktop-features.js
- src/components/desktop-footer.js
- src/components/desktop-header.js
- src/components/desktop-index.js
- src/components/desktop-pricing.js
- src/components/helpscout.js
- src/components/mobile-about.js
- src/components/mobile-features.js
- src/components/mobile-footer.js
- src/components/mobile-header.js
- src/components/mobile-index.js
- src/components/mobile-layout.js
- src/components/mobile-pricing.js
- src/fragments.js
- src/pages/404.js
- src/pages/about.js
- src/pages/features.js
- src/pages/index.js
- src/pages/marketing.js
- src/pages/pricing.js
- yarn.lock
gatsby-plugin-react-i18next 메인 branch에 PR 머지됨.
> gatsby-plugin-react-i18next plug-in 분기 삭제

- package.json
- src/components/desktop-features.js
- src/styles/global.css
- yarn.lock
- sal.js
- gatsby-plugin-scroll-reveal 플러그인
- data-sal attribues
> 더이상 사용하지 않는 의존성 및 코드 제거

- src/components/common.js
- src/components/common.module.css
- src/components/desktop-about.js
- src/components/desktop-features.js
- src/components/desktop-footer.js
- src/components/desktop-header.jsx
- src/components/desktop-index.js
- src/components/desktop-pricing.js
- 1024에서 1194로 변경
- Container1024에서 DesktopBaseContainer로 이름 변경
> Desktop Container 크기 1194로 변경

- src/components/desktop-footer.js
> 데스크탑 푸터 사용사례 하위 메뉴 주소 변경

- gatsby-md-blog-helper.js
- src/components/desktop-postbody.module.css
- src/components/desktop-postlist.jsx
- src/components/desktop-postlist.module.css
- src/components/mobile-postbody.module.css
- src/components/mobile-postlist.jsx
- src/components/mobile-postlist.module.css
1. 블로그 리스트 스타일 오류 일부 수정
2. 인라인 코드 스타일 추가
> 블로그 게시물 리스트의 스타일 오류 수정 & 인라인 코드 스타일 추가

- src/components/common.module.css
- src/components/desktop-about.module.css
- src/components/desktop-features.module.css
- src/components/desktop-footer.module.css
- src/components/desktop-header.module.css
- src/components/desktop-index.module.css
- src/components/desktop-postbody.module.css
- src/components/desktop-postlist.module.css
- src/components/desktop-postview.module.css
- src/components/desktop-pricing.module.css
- src/components/desktop-usecase-footer.module.css
- src/components/language-selector.module.css
- src/components/mobile-about.module.css
- src/components/mobile-features.module.css
- src/components/mobile-footer.module.css
- src/components/mobile-header.module.css
- src/components/mobile-index.module.css
- src/components/mobile-postbody.module.css
- src/components/mobile-postlist.module.css
- src/components/mobile-postview.module.css
- src/components/mobile-pricing.module.css
- src/components/mobile-usecase-footer.module.css
- src/styles/global.css
- --color-font-gray1 -> --color-black
- --color-font-primary -> --color-gray1
- --color-feature-bg-green -> --color-green-10으로 통일
- --color-bg-light -> --color-gray5
---
- 작게 만들어라
- 한 가지만 해라.
> css 변수명 정리

- locales/ko/url.json
- src/components/desktop-footer.js
- src/components/mobile-footer.js
- 한국어 페이지에서 자주묻는질문 / 매뉴얼 메뉴 노출 안함.
- 카카오톡 채널 이름 변경
- 한국어 고객센터 주소 변경
- 작게 만들어라
- 한 가지만 해라.
> 데스크탑/모바일 푸터 변경

- locales/en/footer.json
- locales/es/footer.json
- locales/id/footer.json
- static/tos_en.html
> Chore: 다국어 대표번호 표기에 02 지역번호

- src/components/mobile-postlist.jsx
- src/components/mobile-postlist.module.css
> 블로그 게시물 목록(모바일) - 게시물 카드 aspect ratio 고정

- locales/en/index.json
- locales/es/index.json
- locales/id/index.json
> 컨설팅 버튼 영어 문구 변경

- locales/ko/index.json
> 컨설팅 버튼 한국어 문구 변경

- locales/en/url.json
- locales/es/url.json
- locales/id/url.json
- locales/ko/url.json
> youtube 링크 변경

- src/components/YoutubePopup.js
- src/components/common.js
- 모바일에서 자동재생을 포기하더라도 음소거 안 하도록 함.
> chore: 소개 영상 음소거 안 하도록 설정.

- src/components/helpscout.js
> 모바일에서도 비콘 노출.

- locales/en/footer.json
- locales/ko/footer.json
- src/components/desktop-index.module.css
- src/components/mobile-footer.js
- src/components/mobile-footer.module.css
- src/components/mobile-index.js
> chore: 모바일 index 및 footer에 컨설팅, 다운로드 버튼 추가

- locales/en/footer.json
- src/components/desktop-footer.js
- src/components/mobile-footer.js
> chore(footer-en): WhatsApp 제거

- src/components/constants.js
https://calendly.com/boxhero/free-consulting → https://boxhero-invt.typeform.com/to/BAjooflm
https://whattime.co.kr/boxhero/demo → https://boxhero-invt.typeform.com/to/AgYWMNU8
> chore(index): 데모 예약 버튼 링크 변경

- locales/en/footer.json
- locales/en/url.json
- locales/ko/footer.json
- locales/ko/url.json
- src/components/desktop-footer.js
- src/components/mobile-footer.js
[영문](https://cdn.bgp.works/boxhero-landing/pdf/BoxHero%20Introduction.pdf) | [국문](https://cdn.bgp.works/boxhero-landing/pdf/%E1%84%87%E1%85%A1%E1%86%A8%E1%84%89%E1%85%B3%E1%84%92%E1%85%B5%E1%84%8B%E1%85%A5%E1%84%85%E1%85%A9%20%E1%84%89%E1%85%A5%E1%84%87%E1%85%B5%E1%84%89%E1%85%B3%20%E1%84%89%E1%85%A9%E1%84%80%E1%85%A2.pdf)
> chore: Footer에 서비스 소개서 링크 추가

- src/components/common.js
> 컨설팅 버튼 제거.
